# Generated by Django 4.1.7 on 2023-05-26 05:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', ckeditor.fields.RichTextField(null=True)),
                ('TARIKH', models.DateField(blank=True, null=True)),
                ('MASA', models.TimeField(blank=True, null=True)),
                ('TEMPAT', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('ANJURAN', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('TUJUAN', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('LATAR_BELAKANG', ckeditor.fields.RichTextField(null=True)),
                ('Objektif_1', ckeditor.fields.RichTextField(null=True)),
                ('Butiran_program', models.TextField(blank=True, default='', max_length=0, null=True)),
                ('Tarikh_A', models.DateField(blank=True, null=True)),
                ('Tempat_A', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('Sasaran_peserta', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('Jawatankuasa_Pelaksana', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('Atur_Cara', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('Implikasi_Kewangan', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('SETIAUSAHA', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('BENDAHARI', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('JAWATANKUASA_PERALATAN_DAN_TEKNIKAL', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('JAWATANKUASA_JEMPUTAN', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('JAWATANKUASA_AKTIVITI', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('Atur_Cara_B', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('Tarikh_B', models.DateField(blank=True, null=True)),
                ('Masa_B', models.TimeField(blank=True, null=True)),
                ('Tempat_B', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('JUMLAH_KESELURUHAN_1', models.IntegerField(blank=True, null=True)),
                ('JUMLAH_KESELURUHAN_2', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Masa_B1', models.TimeField(blank=True, null=True)),
                ('activity_B1', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_form.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='LampiranD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('data', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('modelD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_form.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='LampiranC2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_C1', models.IntegerField(blank=True, null=True)),
                ('value_C1', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('modelC2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_form.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='LampiranC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_1', models.IntegerField(blank=True, null=True)),
                ('value_1', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('modelC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_form.invoice')),
            ],
        ),
    ]
