# Generated by Django 4.1.7 on 2023-05-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Name_1',
            field=models.TextField(blank=True, default='', max_length=50, null=True),
        ),
    ]
