# Generated by Django 4.1.7 on 2023-05-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_form', '0002_invoice_name_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='timbalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIMBALAN_PENGARAH', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('model2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_form.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='setiausaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SETIAUSAHA', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('model3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_form.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='pengarah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PENGARAH', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('model1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_form.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='bendahari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BENDAHARI', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('model4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_form.invoice')),
            ],
        ),
    ]
