# Generated by Django 4.1.7 on 2023-05-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_form', '0003_timbalan_setiausaha_pengarah_bendahari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setiausaha',
            name='model3',
        ),
        migrations.DeleteModel(
            name='bendahari',
        ),
        migrations.DeleteModel(
            name='setiausaha',
        ),
    ]
