# Generated by Django 4.1.7 on 2023-06-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_form', '0004_remove_setiausaha_model3_delete_bendahari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_1', models.ImageField(upload_to='')),
                ('model3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_form.invoice')),
            ],
        ),
    ]
